### ISSUE TITLE
ontouml-lightweight-editor docker image

### ISSUE THREAD

**Issue by jeswr** [nemo-ufes/gufo#12]
I just wanted to note that I have created a docker image for https://github.com/nemo-ufes/ontouml-lightweight-editor and pushed it to https://hub.docker.com/r/jeswr/ontouml if this is of use to anyone.

**Comment by pedropaulofb** [comment]
Hi @jeswr, thank you for your work!

However, please notice that the OntoUML Lighweight Editor (OLED) was discontinued and that the current supported tool is the [OntoUML Visual Paradigm Plugin](https://github.com/OntoUML/ontouml-vp-plugin/) - available to the Visual Paradigm, which has a free version that can be downloaded [from here](https://www.visual-paradigm.com/download/community.jsp).

There have been significant developments in the OntoUML language that are only reflected on the newest tool.

Feel free to get in touch if you need any information about the development of the language or its tools.

**Comment by jeswr** [comment]
Thank you so much for the pointer to OLED - I'll use that now (I was only playing to the editor for an hr or so last night anyhow).

If you have permissions it might be worth linking to OLED on https://ontouml.org/ontouml/tooling/

**Comment by pedropaulofb** [comment]
> If you have permissions it might be worth linking to the plugin at the top of https://ontouml.org/ontouml/tooling/ and in the deprecated OLED repo

Unfortunately I don't. But I'll check that with my colleagues who do. Thanks for pointing that out.
