### ISSUE TITLE
Aspects are documented as being Endurants, which they are not

### ISSUE THREAD

**Issue by plbt5** [nemo-ufes/gufo#13]
**Describe the bug**
In the [documentation](https://nemo-ufes.github.io/gufo/#intrinsicaspects), `Aspect`s are considered Endurants. At the same time, the individuals they instantiate are considered to `inhereIn ConcreteIndividuals`. The latter I concur, but the former is very confusing - at least for me. Particularly, according to the Taxonomy of Individuals gufo considers `Quality`s to be `Aspect`s . However, according to the ontological sextet below (adapted from [1]; part (a) adapted from [2]) `Aspect`s (*) stand on themselves and characterise Endurants.

![OntoSquareAndSextet](https://github.com/nemo-ufes/gufo/assets/8479553/895a16d2-3e0c-4273-8e5d-4f13eede1d3f)

(*) Depicted above, in Figure (a), the _Aspects_ are denoted in [1] as _Quality Universals_ and in [2] as _Moment Universals_; I assume that these are more denotational differences whereas their meaning are equivalent over [1], [2] and gufo. If not, this could be the source of my confusion.

**Expected behavior**
I assume that in the Taxonomy of Individuals, one should consider `Aspect`s at the same level as `Endurant`s, `Event`s and - possibly - `Situation`s.  

If I'm wrong in my conclusions, than I suggest to improve the documentation -- not being able to understand a text is considered a flaw of the text as opposed to an incapability of the reader 😉  

**References**

1. B. Smith, “Against fantology,” in Experience and Analysis, J. C.Marek and M. E. Reicher, Eds. HPT&ÖBV, 2005, pp. 153–170
2. G. M. Miranda, J. P. A. Almeida, G. Guizzardi and C. L. B. Azevedo, "Foundational Choices in Enterprise Architecture: The Case of Capability in Defense Frameworks," 2019

**Comment by ajnelson-nist** [comment]
This appears related to #11 .

**Comment by jpalmeida** [comment]
Paul, you seem to be conflating endurants and substantials.
 
UFO partitions endurants into substantials and moments. gUFO partitions endurants into objects and aspects (with change in terminology, and a slight change in coverage. See http://purl.org/nemo/doc/gufo#Object for how gufo:Object relates to UFO notions.)

So, in sum: Aspects are not objects. But they are endurants (continuants in BFO terminology).

**Comment by plbt5** [comment]
Ah João, thank you, I stand corrected. Indeed I did conflate those, what a rookie mistake :-)

I should understand an endurant as "[Something endures if and only if it persists by being wholly present at different times](https://iep.utm.edu/per-time/)", with its distinction between `Objects` (substantials) and `Aspects` as without and with existential dependence on another endurant. 

My picture above is wrong and had it corrected, removing the conflation of substantials with endurants.

![OntoSquareAndSextet](https://github.com/nemo-ufes/gufo/assets/8479553/9346e335-7985-4e8e-9a90-6294bb613971)
