### ISSUE TITLE
Question: difference between static or dynamic aspects?

### ISSUE THREAD

**Issue by HuibertDeVries** [nemo-ufes/gufo#18]
Is there a way in gUFO to express that an gufo:Aspect is static or dynamic, equivalent to typing Objects as (sub)kind, phase or role?
For example: ShirtSize is a static aspect of a Shirt, while PersonLength is a dynamic aspect of a Person.

**Comment by pedropaulofb** [comment]
Hi @HuibertDeVries, it is possible to specialize all types of kinds using subkind, phase, role, etc. The modification was introduced in [this paper here](https://philarchive.org/archive/PORETI). The existing types of kinds are: functional complex kind, quantity, quality, collective, mode, and relator.

**Comment by jpalmeida** [comment]
It is important not to conflate the rigidity of aspect types with the immutability of aspects. What Pedro Paulo is referring to is the fact that the endurant type taxonomy can be applied to aspect types too (just like it is applied to object types). So you could have phases of aspects. For example, a relational aspect like an Enrollment in a university could go through phases: ActiveEnrollment, InactiveEnrollment. But gUFO has no means to distinguish mutable and immutable aspects (like qualities in the examples you proposed: ShirtSize and PersonLength).

**Comment by HuibertDeVries** [comment]
Hi @pedropaulofb and @jpalmeida, thanks for your answers, now it is clear to me!
