### ISSUE TITLE
How does gUFO classify Individuals like craters, bullet holes, tool marks?

### ISSUE THREAD

**Issue by ManuelSimoes** [nemo-ufes/gufo#23]
How do we classify Individuals like craters, bullet holes, tool marks, etc? Are these IntrinsicAspects? And if so are they Qualities or IntrinsicModes?

**Comment by jpalmeida** [comment]
They are considered in UFO as parts of their hosts (as opposed to aspects inhering in them). The relation between a feature and its host is one of inseparable parthood (see Guizzardi's thesis, e.g., "We say, for instance, that a hole in a piece of cheese is an inseparable part of the cheese, not externally dependent on it.") Note that, gUFO, as a lightweight implementation of UFO does not include a specific object property for *inseparable* parthood, so the more general one should be used directly (or specialized if the application so requires.)
