### ISSUE TITLE
Cardinality constraints on subproperties of gufo:categorizes/gufo:partitions?

### ISSUE THREAD

**Issue by ManuelSimoes** [nemo-ufes/gufo#26]
Is it possible to attach cardinality constraints to subproperties of categorizes/partitions? And if so, what does it mean? 

E.g. PersonRole (0..*) - personRolecategorizesPerson (subpropertyOf gufo:categorizes) - (1..1) Person. 

Would this mean that one instance of PersonRole (e.g. Student) categorizes exactly one instance of Person, and that an instance of Person can be categorized by 0 or more PersonRoles?

**Comment by pedropaulofb** [comment]
`Is it possible to attach cardinality constraints to subproperties of categorizes/partitions? ` 

Yes, it is.

`Would this mean that one instance of PersonRole (e.g. Student) categorizes exactly one instance of Person, and that an instance of Person can be categorized by 0 or more PersonRoles?`

If I got it right, yes, that's correct.

**Comment by jpalmeida** [comment]
@ManuelSimoes you can certainly use all expressiveness in OWL you want!
