### ISSUE TITLE
Incomplete structure when exporting from Visual Paradigm to Protegé

### ISSUE THREAD

**Issue by andredemori** [nemo-ufes/gufo#8]
When exporting from Visual Paradigm using the 'Export to gUFO' option, the complete gUFO structure is not exported. I believe it is deliberate, so just the necessary to represent what is in the modeling is exported.

**For example:**

**1.** when defining a Quality in the conceptual model, then in Protegé I want to assign a value (data property). But the hasQualityValue was not exported, so I have to create it manually or is there any way to export to gUFO by VP with it already created?

**2.** Another example is that all Kinds and Categories are being exported as FunctionalComplex, without going into detail in the Types structure. Is this also on purpose and is it correct?

**Comment by jpalmeida** [comment]
This issue is not related to gUFO directly, but to the OntoUML Visual Paradigm plugin. See [https://github.com/OntoUML/ontouml-vp-plugin/issues](url)
