### ISSUE TITLE
Upgrading to OntoUML 2.0

### ISSUE THREAD

**Issue by machacovaterka** [nemo-ufes/gufo#9]
**Is your feature request related to a problem? Please describe.**
As far as I understand, gUFO is based on an older version and is thus not consistent with the established OntoUML 2.0 version that is used for modelling. Have you thought about upgrading to a newer version to make gUFO consistent with OntoUML 2.0 modeling? I think it could help a lot to use gUFO in practice. Some of the important relationships and stereotypes are missing from gUFO, and so it would be useful to add them.

The main changes would be:
1, Collective, Mode, Quality, Quantity and Relator would be separate stereotypes that are not subtypes of Kind and can have Role and Phase as subtypes.
2, Adding the Containment stereotype.
3, Adding the Derivation stereotype.
4, Mediation would be a separate stereotype.
5, Adding Composition and Aggregation.

I apologize if I missed something and some of these features are already included in gUFO, but I didn't find them.

**Describe the solution you'd like**
Upgrading to OntoUML 2.0 and adding missing stereotypes.

**Comment by pedropaulofb** [comment]
Hi @machacovaterka , 

Seems that you're confusing UFO and OntoUML. While the former is a Foundational Ontology (in simple terms, a domain-independent set of philosophical ontology theories), OntoUML is a UFO-based modeling language. OntoUML stereotypes reflects the ontological distinctions provided by UFO, but they are not the same thing.

gUFO is a lightweight implementation of UFO in OWL, not of OntoUML. That is why the OntoUML stereotypes are not available. While you use OntoUML for conceptual modeling, you use gUFO for implementation.

I am currently working with gUFO because I am developing [a software named Scior](https://github.com/unibz-core/Scior/) for semi-automatically improving the semantics of OWL ontologies using gUFO. If I can help you in something more, please get in touch.

**Comment by machacovaterka** [comment]
I'm sorry @pedropaulofb, I thought it wasn't a problem, because apart from the points I wrote, OntoUML is already expressible via gUFO and can be further worked with, for example using SPARQL. I was just missing these few things, that way I thought it was caused by an older version. I think this issue can be considered resolved now, thank you.

**Comment by pedropaulofb** [comment]
You don't need to be sorry @machacovaterka. You did great. It is always important to make questions. 

If you want to directly work with an OntoUML model in OWL format, please consider using the serialization provided in by the [ontouml-server](https://github.com/OntoUML/ontouml-server).

In addition, check the [ontouml-vp-plugin](https://github.com/OntoUML/ontouml-vp-plugin), which can export OntoUML models to gUFO.

And, finally, we keep the [OntoUML/UFO Catalog](https://github.com/unibz-core/ontouml-models), where you can find many examples of models and also their machine-processable files.

I continue at your disposal to help with any other doubts you may have.

**Comment by pedropaulofb** [comment]
@machacovaterka, I also kindly ask you to [consider contributing](https://github.com/unibz-core/ontouml-models#how-to-contribute) to the OntoUML/UFO Catalog if you create any model.

**Comment by machacovaterka** [comment]
@pedropaulofb I did, in fact, tried the plugin for Visual Paradigm. Unfortunately, there was quite a lot of errors and missing information, often it was different from the gUFO documentation. The models that I tried representing that way had more than half of them wrong or missing. We were discussing a possibility of developing gUFO export for our tool, so models can be exported and than queried via SPARQL. But we would need more changes for this to work, meaning the changes in my first message. Because in the current state, neither VP plugin nor gUFO is very suitable for OntoUML models.

**Comment by pedropaulofb** [comment]
Do you want to have a quick call regarding these problems you are reporting here? The designers of OntoUML are also the ones behind those tools, so they were supposed to work properly. Please send me an email at pfavatobarcelos@unibz.com.

**Comment by pedropaulofb** [comment]
Sorry @machacovaterka, I sent you a wrong email address in my last message, but now I have already edited the message and fixed it.

Also, this is the most recent [OntoUML documentation](https://ontouml.readthedocs.io/). However, it is still outdated. You can find more information using the related [GitHub repository](https://github.com/OntoUML/OntoUML/) and checking the discussions in the issues.

**Comment by machacovaterka** [comment]
@pedropaulofb I will ask others about the call. The documentation you sent me is the one we are using for modelling.

**Comment by pedropaulofb** [comment]
@machacovaterka , ok. Feel free to get in touch if you need.
